language: ruby
rvm:
  - 2.2.2
before_script:
  - "mysql -e 'create database peatio_test;'"
  - "cp ./travis/.travis.database.yml ./config/database.yml"
  - "cp ./travis/.travis.application.yml ./config/application.yml"
  - "cp ./travis/.travis.currencies.yml ./config/currencies.yml"
  - "cp ./travis/.travis.markets.yml ./config/markets.yml"
  - "cp ./config/amqp.yml.example ./config/amqp.yml"
  - "mkdir -p ./tmp/cache"
install:
  - bundle install --without development --path vendor/bundle
script:
  - bundle exec rake db:setup
  - bundle exec rake assets:precompile
  - bundle exec rake daemons:start
  - bundle exec rake daemons:status
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
# notifications:
#   slack: peatio:F2FWrCANEK3QcjHC16OO541l
