# affected /admin/ deposits methods
- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3

# - id: 400
#   key: bank
#   currency: cny
#   sort_order: 2
#   bank_accounts:
#     -
#       bank: 'Your Bank Name'
#       branch: 'Your Bank Branch'
#       holder: 'Your Account Holder'
#       account: 'Your Account Number'
- id: 500
  key: netpay
  currency: cny
  sort_order: 2
  
- id: 600
  key: ether
  sort_order: 4
  currency: eth
  min_confirm: 1
  max_confirm: 6

- id: 900
  key: euro
  currency: eur
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'